-- ===========================================================================
-- ViceCityHub seed data — GENERATED from src/lib/mock-data.ts
-- Regenerate with: node scripts/gen-seed.mjs
-- Safe to re-run: content tables upsert by slug; carousel is rebuilt.
-- ===========================================================================

-- news (6)
insert into news (slug, title, description, body, excerpt, category, author, images, status, read_minutes, trending, created_at, updated_at) values
  ('gta-6-release-date-november-19-2026', 'GTA 6 Confirmed for November 19, 2026', 'Rockstar Games confirms Grand Theft Auto VI will launch on November 19, 2026, after moving from its earlier spring target.', 'Rockstar Games has confirmed that Grand Theft Auto VI will release on November 19, 2026 for PlayStation 5 and Xbox Series X|S. The date follows an earlier window of May 26, 2026 that was announced alongside the second trailer.

In its statement, Rockstar thanked players for their patience and said the additional time is needed to finish the game with the level of polish it requires. Parent company Take-Two has repeatedly described GTA VI as the most ambitious project in the studio''s history.

A PC version was not announced for launch — consistent with previous Rockstar releases, where PC has historically followed the console debut.', 'Rockstar pushed the date from May 26 to November 19, 2026, asking fans for extra patience to deliver the level of polish the game demands.', 'Release', 'Editorial Desk', ARRAY['news-release-date', 'news-release-2']::text[], 'confirmed', 4, true, '2025-11-06T00:00:00.000Z', '2025-11-06T00:00:00.000Z'),
  ('trailer-2-everything-revealed', 'Trailer 2 Breakdown: Everything Rockstar Revealed', 'The second official trailer for GTA 6 arrived on May 6, 2025, expanding the cast and showing far more of the state of Leonida.', 'Rockstar released the second official trailer for Grand Theft Auto VI on May 6, 2025. It expanded heavily on the world of Leonida — a fictional state inspired by Florida — and introduced a wider supporting cast alongside leads Jason and Lucia.

The trailer showcased Vice City''s neon nightlife, the swamps and wetlands of the interior, the island chain of the Leonida Keys, and a range of characters tied to the criminal underworld. Rockstar also published character bios on its website the same day, naming figures such as Cal Hampton, Boobie Ike, Dre''Quan Priest, Raul Bautista and Brian Heder.', 'From Jason and Lucia''s relationship to a sun-soaked tour of Leonida, the second trailer gave the deepest look yet at GTA 6.', 'Trailer', 'Coverage Team', ARRAY['news-trailer2', 'news-trailer2-b', 'news-trailer2-c']::text[], 'confirmed', 7, true, '2025-05-06T00:00:00.000Z', '2025-05-07T00:00:00.000Z'),
  ('jason-and-lucia-dual-protagonists', 'Meet Jason and Lucia: GTA 6''s Dual Protagonists', 'For the first time in the series, Grand Theft Auto VI stars a playable female lead — Lucia — alongside her partner Jason.', 'Grand Theft Auto VI centers on two protagonists: Jason Duval and Lucia Caminos. Lucia is the first female protagonist in the mainline series, introduced in the first trailer inside a Leonida correctional facility.

Rockstar has described the pair as partners bound together by circumstance and loyalty — a relationship the studio has likened to a modern Bonnie and Clyde. The dual-protagonist structure builds on the character-switching foundations of Grand Theft Auto V, though Rockstar has not detailed exactly how switching will work this time.', 'Rockstar frames Jason and Lucia as a modern Bonnie-and-Clyde duo whose partnership anchors the story.', 'Characters', 'Story Desk', ARRAY['news-jason-lucia', 'news-duo-2']::text[], 'confirmed', 5, true, '2023-12-05T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('leonida-state-confirmed-locations', 'The State of Leonida: Every Confirmed Region', 'Vice City is just the start — Rockstar has named several regions across the fictional state of Leonida.', 'Grand Theft Auto VI is set in the fictional U.S. state of Leonida, inspired by Florida. Its centerpiece is a modern Vice City, but Rockstar''s trailers and website point to a far wider map.

Named regions include the island chain of the Leonida Keys, the wetlands of Grassrivers, the faded coastal town of Port Gellhorn, and other areas across the state. Rockstar has called it the largest and most detailed world it has ever created.', 'Vice City, the Leonida Keys, Grassrivers, Port Gellhorn and more make up the largest world Rockstar has built.', 'World', 'Map Team', ARRAY['news-leonida', 'news-leonida-2']::text[], 'trailer_inferred', 6, false, '2025-05-09T00:00:00.000Z', '2025-05-10T00:00:00.000Z'),
  ('gta-6-pc-version-what-we-know', 'GTA 6 on PC: What We Know (and Don''t)', 'A PC version has not been confirmed for launch. Here''s why most expect it to follow — and when.', 'As of now, Grand Theft Auto VI is confirmed only for PlayStation 5 and Xbox Series X|S. Rockstar has not announced a PC version.

That mirrors the studio''s pattern: Grand Theft Auto V launched on consoles in 2013 and only reached PC in 2015. Most observers expect a PC release to follow GTA VI''s console debut, but any timing remains pure speculation until Rockstar says otherwise.', 'History suggests a PC port arrives after the console launch, but Rockstar has made no PC announcement.', 'Platforms', 'Tech Desk', ARRAY['news-pc']::text[], 'speculation', 4, false, '2025-11-08T00:00:00.000Z', '2025-11-08T00:00:00.000Z'),
  ('gta-online-future-after-gta-6', 'What Happens to GTA Online After GTA 6?', 'Rockstar has been quiet on online plans for GTA 6 — but the community has plenty of theories.', 'Grand Theft Auto Online became one of the most successful live-service games of its era, so attention naturally turns to what an online component for GTA VI might look like.

Rockstar has not detailed any online plans for Grand Theft Auto VI. Everything from a fresh online world to continued support for the existing GTA Online remains speculation at this stage.', 'An evolving online mode seems likely given GTA Online''s success, though nothing has been confirmed.', 'Online', 'Community Desk', ARRAY['news-online']::text[], 'speculation', 3, false, '2025-12-01T00:00:00.000Z', '2025-12-01T00:00:00.000Z')
on conflict (slug) do nothing;

-- guides (6)
insert into guides (slug, title, description, body, category, difficulty, featured, images, status, created_at, updated_at) values
  ('gta-6-release-date-everything-confirmed', 'GTA 6 Release Date: Everything Confirmed', 'The full timeline — from the 2023 reveal to the confirmed November 19, 2026 launch.', 'Grand Theft Auto VI was first revealed on December 4, 2023 with its debut trailer. A second trailer on May 6, 2025 announced a release window of May 26, 2026, which Rockstar later moved to its confirmed date of November 19, 2026.

The game launches on PlayStation 5 and Xbox Series X|S. No PC version has been announced for launch.', 'Release', 'Beginner', true, ARRAY['guide-release', 'guide-release-2']::text[], 'confirmed', '2025-11-07T00:00:00.000Z', '2025-11-07T00:00:00.000Z'),
  ('who-are-jason-and-lucia', 'Who Are Jason and Lucia? Protagonists Explained', 'Everything Rockstar has revealed about GTA 6''s dual leads and their relationship.', 'Jason Duval and Lucia Caminos are the two playable protagonists of Grand Theft Auto VI. Lucia is the series'' first female lead.

Rockstar''s bios describe Jason as someone who grew up around grifters and wants an easy life, and Lucia as someone who has fought for everything she has. Their partnership drives the story.', 'Characters', 'Beginner', true, ARRAY['guide-protagonists']::text[], 'confirmed', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('leonida-regions-and-real-world-inspirations', 'Leonida Regions & Their Real-World Inspirations', 'A tour of every named region in Leonida and the Florida locations that inspired them.', 'Leonida is modeled on Florida. Vice City draws on Miami; the Leonida Keys mirror the Florida Keys; Grassrivers evokes the Everglades; and Port Gellhorn channels the Florida Panhandle.

This guide breaks down each named area, what we''ve seen of it, and how it maps to the real world.', 'World', 'Intermediate', true, ARRAY['guide-leonida', 'guide-leonida-2']::text[], 'trailer_inferred', '2025-05-12T00:00:00.000Z', '2025-05-12T00:00:00.000Z'),
  ('gta-6-platforms-and-system-requirements', 'GTA 6 Platforms & System Requirements', 'Which consoles run GTA 6 at launch, and what we can guess about an eventual PC release.', 'Grand Theft Auto VI launches on PlayStation 5 and Xbox Series X|S. There is no last-gen (PS4 / Xbox One) version.

A PC release has not been announced. Any PC system requirements are pure speculation until Rockstar confirms a port.', 'Platforms', 'Beginner', false, ARRAY['guide-platforms']::text[], 'confirmed', '2025-11-09T00:00:00.000Z', '2025-11-09T00:00:00.000Z'),
  ('trailer-1-vs-trailer-2-what-changed', 'Trailer 1 vs Trailer 2: What Changed', 'Side-by-side analysis of the two official trailers and the new details the second one revealed.', 'The first trailer (December 2023) introduced Vice City, Lucia, and the tone of the game. The second trailer (May 2025) widened the lens — showing more of Leonida, a larger supporting cast, and a major visual leap.

This guide compares the two shot by shot.', 'Analysis', 'Advanced', false, ARRAY['guide-trailers']::text[], 'trailer_inferred', '2025-05-14T00:00:00.000Z', '2025-05-14T00:00:00.000Z'),
  ('gta-6-pre-order-and-editions', 'GTA 6 Pre-Orders & Editions: What to Expect', 'Pre-orders aren''t live yet — here''s what Rockstar''s past launches suggest may be coming.', 'Rockstar has not opened pre-orders or detailed special editions for Grand Theft Auto VI. Based on prior launches, expect standard and premium editions with in-game bonuses to be announced closer to release.

Treat any edition details circulating now as unconfirmed.', 'Buying', 'Beginner', false, ARRAY['guide-preorder']::text[], 'speculation', '2025-12-02T00:00:00.000Z', '2025-12-02T00:00:00.000Z')
on conflict (slug) do nothing;

-- vehicles (6)
insert into vehicles (slug, title, description, body, class, manufacturer, images, status, top_speed, created_at, updated_at) values
  ('vice-city-convertible', 'Vintage Convertible', 'A classic drop-top cruising Vice City''s beachfront — a recurring image in both trailers.', 'Open-top convertibles feature prominently in GTA 6''s marketing, cruising Ocean Drive against neon and palms. Rockstar has not named specific models, so exact stats are estimates based on the archetype.', 'Convertible', 'Unconfirmed', ARRAY['vehicle-convertible']::text[], 'trailer_inferred', 130, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('muscle-car', 'American Muscle Car', 'Aggressive two-door muscle, a staple of the series, glimpsed throughout the trailers.', 'Muscle cars are a Grand Theft Auto staple and appear in GTA 6 footage. No specific model has been confirmed; performance figures here are indicative of the class.', 'Muscle', 'Unconfirmed', ARRAY['vehicle-muscle']::text[], 'trailer_inferred', 140, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('exotic-supercar', 'Exotic Supercar', 'Low-slung, mid-engine exotics for the high-roller side of Leonida — expected to return.', 'Supercars have headlined every modern GTA. While none are officially named for GTA 6 yet, the class is all but certain to return. Stats shown are placeholders for the archetype.', 'Super', 'Unconfirmed', ARRAY['vehicle-super']::text[], 'speculation', 165, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('street-motorcycle', 'Street Motorcycle', 'Nimble two-wheelers for weaving through Vice City traffic, seen in trailer footage.', 'Motorcycles appear in GTA 6 footage and are a longtime series fixture. Specific bikes have not been named; figures here reflect the class.', 'Motorcycle', 'Unconfirmed', ARRAY['vehicle-motorcycle']::text[], 'trailer_inferred', 150, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('airboat', 'Swamp Airboat', 'Fan-powered flat-bottom boats built for the shallow wetlands of Grassrivers.', 'The trailers show airboats skimming across the wetlands of Leonida''s interior — a vehicle type well suited to the Everglades-inspired Grassrivers region. Specifics are unconfirmed.', 'Boat', 'Unconfirmed', ARRAY['vehicle-airboat']::text[], 'trailer_inferred', 70, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('pickup-truck', 'Off-Road Pickup', 'Rugged pickups for the rural backroads and swamps beyond the city limits.', 'Pickups and off-roaders fit Leonida''s rural interior and appear in trailer scenes outside the city. No models are officially confirmed; stats are indicative.', 'Off-Road', 'Unconfirmed', ARRAY['vehicle-pickup']::text[], 'trailer_inferred', 110, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z')
on conflict (slug) do nothing;

-- characters (8)
insert into characters (slug, title, description, body, role, affiliation, images, status, voice_actor, created_at, updated_at) values
  ('lucia-caminos', 'Lucia Caminos', 'The series'' first female protagonist — tough, loyal, and fighting for a way out.', 'Lucia Caminos is one of the two playable protagonists of Grand Theft Auto VI and the first female lead in the mainline series. Introduced in the first trailer inside a Leonida correctional facility, Rockstar describes her as someone who has had to fight for everything she has. Her loyalty to Jason anchors the story.', 'Protagonist', 'Jason & Lucia', ARRAY['char-lucia', 'char-lucia-2']::text[], 'confirmed', NULL, '2023-12-04T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('jason-duval', 'Jason Duval', 'Lucia''s partner — grew up around grifters and just wants an easy life that never comes.', 'Jason Duval is the second playable protagonist of Grand Theft Auto VI. Rockstar''s bio says he grew up around grifters and crooks and learned early that money has to come from somewhere. Living in the Leonida Keys, he wants a simple life — but trouble keeps finding him and Lucia.', 'Protagonist', 'Jason & Lucia', ARRAY['char-jason', 'char-jason-2']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('cal-hampton', 'Cal Hampton', 'A paranoid friend of Jason who''s happiest behind a police scanner and a stack of conspiracies.', 'Cal Hampton is described in Rockstar''s bios as an associate of Jason who is most comfortable at home, monitoring radio chatter and chasing conspiracy theories. He provides a connection to information from the fringes.', 'Associate', 'Jason''s circle', ARRAY['char-cal']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('boobie-ike', 'Boobie Ike', 'A self-made businessman turning street credibility into real estate and a music empire.', 'Boobie Ike is a Leonida businessman who, per Rockstar''s bio, came up the hard way and is parlaying his reputation into legitimate ventures — including real estate and a recording studio tied to the local music scene.', 'Businessman', 'Leonida underworld', ARRAY['char-boobie']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('drequan-priest', 'Dre''Quan Priest', 'An ambitious rap entrepreneur chasing a breakout out of Leonida''s music scene.', 'Dre''Quan Priest is an up-and-coming music entrepreneur connected to Boobie Ike''s world. Rockstar frames him as someone with a real shot at turning local talent — including the duo Real Dimez — into something much bigger.', 'Music Mogul', 'Leonida music scene', ARRAY['char-drequan']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('real-dimez', 'Real Dimez', 'A social-media-famous rap duo riding their viral moment for all it''s worth.', 'Real Dimez is a female rap duo tied to Dre''Quan Priest''s ambitions. Rockstar''s bios present them as internet-famous performers leveraging viral attention in Leonida''s music scene.', 'Rap Duo', 'Leonida music scene', ARRAY['char-realdimez']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('raul-bautista', 'Raul Bautista', 'A career robber assembling a crew for scores far bigger than he can pull alone.', 'Raul Bautista is described by Rockstar as an experienced robber putting together a crew for increasingly ambitious jobs — a thread that pulls Jason and Lucia toward serious risk.', 'Robber', 'Bautista crew', ARRAY['char-raul']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('brian-heder', 'Brian Heder', 'A drug-running operator working the waterways beyond the reach of the law.', 'Brian Heder is a trafficker operating out of Leonida''s coast and waterways, per Rockstar''s character bios — one of the figures whose business intersects with Jason''s.', 'Trafficker', 'Leonida underworld', ARRAY['char-brian']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z')
on conflict (slug) do nothing;

-- locations (6)
insert into locations (slug, title, description, body, region, type, coordinates, images, status, created_at, updated_at) values
  ('vice-city', 'Vice City', 'The neon heart of Leonida — a sprawling coastal metropolis reborn for a new era.', 'Vice City returns as the centerpiece of Grand Theft Auto VI: a modern metropolis inspired by Miami, full of beaches, Art Deco facades, nightlife, and a glittering skyline. It anchors the state of Leonida.', 'Vice City', 'City', '{"x":64,"y":68}'::jsonb, ARRAY['loc-vicecity', 'loc-vicecity-2']::text[], 'confirmed', '2023-12-04T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('leonida-keys', 'Leonida Keys', 'A laid-back island chain off the southern coast — Jason''s home turf.', 'The Leonida Keys are an island chain inspired by the Florida Keys. Sun-bleached, slow-paced, and surrounded by water, the Keys are where Jason lives at the start of the game.', 'Leonida Keys', 'Islands', '{"x":58,"y":90}'::jsonb, ARRAY['loc-keys']::text[], 'confirmed', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('grassrivers', 'Grassrivers', 'Sprawling wetlands and swamp inspired by the Everglades — airboat country.', 'Grassrivers is the wetlands region of Leonida, drawing on Florida''s Everglades. Trailer footage shows airboats, marshland, and wildlife across its waterlogged interior.', 'Grassrivers', 'Wetlands', '{"x":46,"y":76}'::jsonb, ARRAY['loc-grassrivers']::text[], 'trailer_inferred', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('port-gellhorn', 'Port Gellhorn', 'A faded working-class coastal town in the north of the state.', 'Port Gellhorn is a coastal town inspired by the Florida Panhandle — a grittier, working-class counterpoint to Vice City''s glamour, named in Rockstar''s materials.', 'Port Gellhorn', 'Town', '{"x":22,"y":26}'::jsonb, ARRAY['loc-portgellhorn']::text[], 'trailer_inferred', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('ambrosia', 'Ambrosia', 'An inland community across Leonida''s central stretch.', 'Ambrosia is among the areas referenced for Leonida''s interior. Details remain limited, but it points to the breadth of the state beyond Vice City.', 'Ambrosia', 'Town', '{"x":40,"y":48}'::jsonb, ARRAY['loc-ambrosia']::text[], 'speculation', '2025-05-20T00:00:00.000Z', '2025-05-20T00:00:00.000Z'),
  ('mount-kalliga', 'Mount Kalliga', 'Elevated wilderness and lookout country in the north of Leonida.', 'Mount Kalliga represents Leonida''s higher, wilder terrain — a contrast to the flat coast and wetlands. Specifics are still emerging from trailer analysis and community mapping.', 'Mount Kalliga', 'Wilderness', '{"x":52,"y":30}'::jsonb, ARRAY['loc-kalliga']::text[], 'speculation', '2025-05-22T00:00:00.000Z', '2025-05-22T00:00:00.000Z')
on conflict (slug) do nothing;

-- carousel_items (4)
delete from carousel_items;
insert into carousel_items (title, category, image, href, date, "order", active, status) values
  ('GTA 6 Launches November 19, 2026', 'Release', 'news-release-date', '/news/gta-6-release-date-november-19-2026', '2025-11-06T00:00:00.000Z', 1, true, 'confirmed'),
  ('Trailer 2: Everything Rockstar Revealed', 'Trailer', 'news-trailer2', '/news/trailer-2-everything-revealed', '2025-05-06T00:00:00.000Z', 2, true, 'confirmed'),
  ('Meet Jason & Lucia, the Dual Protagonists', 'Characters', 'news-jason-lucia', '/news/jason-and-lucia-dual-protagonists', '2023-12-05T00:00:00.000Z', 3, true, 'confirmed'),
  ('The State of Leonida: Confirmed Regions', 'World', 'news-leonida', '/news/leonida-state-confirmed-locations', '2025-05-09T00:00:00.000Z', 4, true, 'trailer_inferred');
