-- ===========================================================================
-- ViceCityHub seed data — GENERATED from src/lib/mock-data.ts
-- Regenerate with: node scripts/gen-seed.mjs
-- Safe to re-run: content tables upsert by slug; carousel is rebuilt.
-- ===========================================================================

-- news (11)
insert into news (slug, title, description, body, excerpt, category, author, images, status, read_minutes, trending, created_at, updated_at) values
  ('gta-6-release-date-november-19-2026', 'GTA 6 Confirmed for November 19, 2026', 'Rockstar Games confirms Grand Theft Auto VI will launch on November 19, 2026, after moving from its earlier spring target.', 'Rockstar Games has confirmed that Grand Theft Auto VI will release on November 19, 2026 for PlayStation 5 and Xbox Series X|S. The date follows an earlier window of May 26, 2026 that was announced alongside the second trailer.

In its statement, Rockstar thanked players for their patience and said the additional time is needed to finish the game with the level of polish it requires. Parent company Take-Two has repeatedly described GTA VI as the most ambitious project in the studio''s history.

A PC version was not announced for launch — consistent with previous Rockstar releases, where PC has historically followed the console debut.', 'Rockstar pushed the date from May 26 to November 19, 2026, asking fans for extra patience to deliver the level of polish the game demands.', 'Release', 'Editorial Desk', ARRAY['news-release-date', 'news-release-2']::text[], 'confirmed', 4, true, '2025-11-06T00:00:00.000Z', '2025-11-06T00:00:00.000Z'),
  ('trailer-2-everything-revealed', 'Trailer 2 Breakdown: Everything Rockstar Revealed', 'The second official trailer for GTA 6 arrived on May 6, 2025, expanding the cast and showing far more of the state of Leonida.', 'Rockstar released the second official trailer for Grand Theft Auto VI on May 6, 2025, alongside dozens of new screenshots — its deepest look at Leonida yet.

Locations: the trailer toured Vice City''s neon nightlife, the Everglades-style swamps of Grassrivers, the faded coast of Port Gellhorn, the industrial town of Ambrosia, and the island chain of the Leonida Keys.

Story: a bank robbery appears to kick off the plot, Lucia is shown out on parole with an ankle monitor, and corrupt police recur throughout. Rockstar published bios for Cal Hampton, Boobie Ike, Dre''Quan Priest, Real Dimez, Raul Bautista and Brian Heder.

Graphics: the trailer showed a major technical leap — vastly improved hair physics, high-quality water with real-time deformation, enormous draw distances, and detailed lighting and shadows.', 'From Jason and Lucia''s relationship to a sun-soaked tour of Leonida, the second trailer gave the deepest look yet at GTA 6.', 'Trailer', 'Coverage Team', ARRAY['news-trailer2', 'news-trailer2-b', 'news-trailer2-c']::text[], 'confirmed', 7, true, '2025-05-06T00:00:00.000Z', '2025-05-07T00:00:00.000Z'),
  ('jason-and-lucia-dual-protagonists', 'Meet Jason and Lucia: GTA 6''s Dual Protagonists', 'For the first time in the series, Grand Theft Auto VI stars a playable female lead — Lucia — alongside her partner Jason.', 'Grand Theft Auto VI centers on two protagonists: Jason Duval and Lucia Caminos. Lucia is the first female protagonist in the mainline series, introduced in the first trailer inside a Leonida correctional facility.

Rockstar has described the pair as partners bound together by circumstance and loyalty — a relationship the studio has likened to a modern Bonnie and Clyde. The dual-protagonist structure builds on the character-switching foundations of Grand Theft Auto V, though Rockstar has not detailed exactly how switching will work this time.', 'Rockstar frames Jason and Lucia as a modern Bonnie-and-Clyde duo whose partnership anchors the story.', 'Characters', 'Story Desk', ARRAY['news-jason-lucia', 'news-duo-2']::text[], 'confirmed', 5, true, '2023-12-05T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('leonida-state-confirmed-locations', 'The State of Leonida: Every Confirmed Region', 'Vice City is just the start — Rockstar has named several regions across the fictional state of Leonida.', 'Grand Theft Auto VI is set in the fictional U.S. state of Leonida, inspired by Florida. Its centerpiece is a modern Vice City, but Rockstar''s trailers and website point to a far wider map.

Named regions include the island chain of the Leonida Keys, the wetlands of Grassrivers, the faded coastal town of Port Gellhorn, and other areas across the state. Rockstar has called it the largest and most detailed world it has ever created.', 'Vice City, the Leonida Keys, Grassrivers, Port Gellhorn and more make up the largest world Rockstar has built.', 'World', 'Map Team', ARRAY['news-leonida', 'news-leonida-2']::text[], 'trailer_inferred', 6, false, '2025-05-09T00:00:00.000Z', '2025-05-10T00:00:00.000Z'),
  ('gta-6-pc-version-what-we-know', 'GTA 6 on PC: What We Know (and Don''t)', 'A PC version has not been confirmed for launch. Here''s why most expect it to follow — and when.', 'As of now, Grand Theft Auto VI is confirmed only for PlayStation 5 and Xbox Series X|S. Rockstar has not announced a PC version.

That mirrors the studio''s pattern: Grand Theft Auto V launched on consoles in 2013 and only reached PC in 2015. Most observers expect a PC release to follow GTA VI''s console debut, but any timing remains pure speculation until Rockstar says otherwise.', 'History suggests a PC port arrives after the console launch, but Rockstar has made no PC announcement.', 'Platforms', 'Tech Desk', ARRAY['news-pc']::text[], 'speculation', 4, false, '2025-11-08T00:00:00.000Z', '2025-11-08T00:00:00.000Z'),
  ('gta-online-future-after-gta-6', 'What Happens to GTA Online After GTA 6?', 'Rockstar has been quiet on online plans for GTA 6 — but the community has plenty of theories.', 'Grand Theft Auto Online became one of the most successful live-service games of its era, so attention naturally turns to what an online component for GTA VI might look like.

Rockstar has not detailed any online plans for Grand Theft Auto VI. Everything from a fresh online world to continued support for the existing GTA Online remains speculation at this stage.', 'An evolving online mode seems likely given GTA Online''s success, though nothing has been confirmed.', 'Online', 'Community Desk', ARRAY['news-online']::text[], 'speculation', 3, false, '2025-12-01T00:00:00.000Z', '2025-12-01T00:00:00.000Z'),
  ('gta-6-graphics-new-rage-engine', 'GTA 6 Graphics: Inside the New RAGE Engine', 'Trailer 2 revealed a generational leap — ray tracing, lifelike water, hair physics, and procedural detail.', 'Trailer 2 and Rockstar''s screenshots showcased a major technical leap on a new version of the RAGE engine (informally dubbed ''RAGE 9'' by the community).

Water is rendered with high-quality meshes that deform realistically as boats cut through them, with translucency that varies by water type. Shadows are detailed enough to capture individual hair strands and netted windows without shimmering, and large panning shots reveal huge draw distances with smooth world streaming.

Rockstar developers have teased cutting-edge tech including ray tracing, ray-traced global illumination, and procedural generation for objects and environments. Hair physics in particular saw a dramatic improvement over Trailer 1.', 'From ray-traced global illumination to deformable water and improved hair physics, GTA 6 pushes Rockstar''s RAGE engine to a new level.', 'Tech', 'Tech Desk', ARRAY['news-graphics']::text[], 'trailer_inferred', 6, true, '2025-05-15T00:00:00.000Z', '2025-05-15T00:00:00.000Z'),
  ('gta-6-pre-orders-editions-detailed', 'GTA 6 Pre-Orders & Editions Detailed', 'Pre-orders opened June 25, 2026 with two editions and a Vintage Vice City bonus pack.', 'Rockstar opened Grand Theft Auto VI pre-orders on June 25, 2026 across the PlayStation Store, Microsoft Store, Rockstar Games Store, and global retailers.

Two editions are available: the Standard Edition at $79.99 and the Ultimate Edition at $99.99, which adds premium vehicles, weapons, apparel, and story content woven across the game. There is no Special or Collector''s Edition.

Every pre-order includes the Vintage Vice City Pack — a ''55 Vapid Stanier, an Ocean Beach garage, and vintage outfits for Jason and Lucia. The game launches November 19, 2026 on PS5, PS5 Pro, and Xbox Series X|S; physical copies (a code in a box) hit retail from November 12 to support pre-loading.', 'Standard ($79.99) and Ultimate ($99.99) editions, plus a Vintage Vice City Pack for all pre-orders — no Collector''s Edition this time.', 'Release', 'Editorial Desk', ARRAY['news-preorder']::text[], 'confirmed', 4, true, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('gta-6-plays-best-on-ps5-sony', 'Sony Says GTA 6 ''Plays Best on PS5''', 'Sony is touting PS5-specific perks for GTA 6 — DualSense haptics, 3D audio, and ultra-fast load times.', 'Posts circulating from the community point to Sony promoting PlayStation 5 as the best way to play Grand Theft Auto VI, reportedly via a PlayStation Blog post.

The highlighted perks include the DualSense controller''s haptic feedback and integrated speaker, Tempest 3D AudioTech to ''surround yourself in the distinct soundscapes of Leonida,'' and near-instant load times thanks to the PS5''s ultra-high-speed SSD.

It''s worth noting these are platform-marketing points, and it isn''t yet clear how much the experience will actually differ from the Xbox Series X|S version. Rockstar has not detailed platform-specific features itself.', 'DualSense haptic feedback, Tempest 3D AudioTech, and near-instant SSD load times headline Sony''s GTA 6 pitch — though how much differs from Xbox is unclear.', 'Platforms', 'Platforms Desk', ARRAY['news-ps5']::text[], 'speculation', 4, true, '2026-06-28T00:00:00.000Z', '2026-06-28T00:00:00.000Z'),
  ('gta-6-map-size-comparison', 'How Big Is GTA 6''s Map? ~4x Larger Than GTA V', 'Community estimates put Leonida at roughly 125 km²+ — about four times the size of GTA V''s map.', 'Map-size comparisons making the rounds estimate Grand Theft Auto VI''s state of Leonida at roughly 125 km² or more — about four times the size of GTA V''s ~81 km² map, and far larger than San Andreas (~36 km²) or the original Vice City (~16 km²).

These figures are estimates based on in-game data, developer leaks, and community analysis, not official numbers. Rockstar has only said Leonida is the largest and most detailed world it has built. Treat exact sizes as unconfirmed until launch.', 'Based on leaks and community analysis, GTA 6''s Leonida is estimated at ~125 km²+, dwarfing GTA V (~81 km²) and every previous entry.', 'World', 'Map Team', ARRAY['news-mapsize']::text[], 'speculation', 3, true, '2026-06-28T00:00:00.000Z', '2026-06-28T00:00:00.000Z'),
  ('vice-city-stanier-returns', 'Vice City''s Iconic Stanier Returns in GTA 6', 'The classic Vapid Stanier sedan makes its comeback — and you can get a vintage ''55 model free with pre-orders.', 'The Vapid Stanier — a Grand Theft Auto staple since the original Vice City era — is making its return in GTA 6.

A vintage ''55 Vapid Stanier is confirmed as part of the Vintage Vice City Pack included with every pre-order, alongside an Ocean Beach garage. It''s the first GTA 6 vehicle Rockstar has named, and a nod to longtime fans of the series'' Miami-inspired roots.', 'A staple since the original Vice City, the Stanier returns in GTA 6, with a vintage ''55 Vapid Stanier bundled into the pre-order Vintage Vice City Pack.', 'Vehicles', 'Garage', ARRAY['news-stanier']::text[], 'confirmed', 3, false, '2026-06-28T00:00:00.000Z', '2026-06-28T00:00:00.000Z')
on conflict (slug) do update set title = excluded.title, description = excluded.description, body = excluded.body, excerpt = excluded.excerpt, category = excluded.category, author = excluded.author, status = excluded.status, read_minutes = excluded.read_minutes, trending = excluded.trending, created_at = excluded.created_at, updated_at = excluded.updated_at;

-- guides (6)
insert into guides (slug, title, description, body, category, difficulty, featured, images, status, created_at, updated_at) values
  ('gta-6-release-date-everything-confirmed', 'GTA 6 Release Date: Everything Confirmed', 'The full timeline — from the 2023 reveal to the confirmed November 19, 2026 launch.', 'Grand Theft Auto VI was first revealed on December 4, 2023 with its debut trailer. A second trailer on May 6, 2025 announced a release window of May 26, 2026, which Rockstar later moved to its confirmed date of November 19, 2026.

The game launches on PlayStation 5 and Xbox Series X|S. No PC version has been announced for launch.', 'Release', 'Beginner', true, ARRAY['guide-release', 'guide-release-2']::text[], 'confirmed', '2025-11-07T00:00:00.000Z', '2025-11-07T00:00:00.000Z'),
  ('who-are-jason-and-lucia', 'Who Are Jason and Lucia? Protagonists Explained', 'Everything Rockstar has revealed about GTA 6''s dual leads and their relationship.', 'Jason Duval and Lucia Caminos are the two playable protagonists of Grand Theft Auto VI. Lucia is the series'' first female lead.

Rockstar''s bios describe Jason as someone who grew up around grifters and wants an easy life, and Lucia as someone who has fought for everything she has. Their partnership drives the story.', 'Characters', 'Beginner', true, ARRAY['guide-protagonists']::text[], 'confirmed', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('leonida-regions-and-real-world-inspirations', 'Leonida Regions & Their Real-World Inspirations', 'A tour of every named region in Leonida and the Florida locations that inspired them.', 'Leonida is modeled on Florida. Vice City draws on Miami; the Leonida Keys mirror the Florida Keys; Grassrivers evokes the Everglades; and Port Gellhorn channels the Florida Panhandle.

This guide breaks down each named area, what we''ve seen of it, and how it maps to the real world.', 'World', 'Intermediate', true, ARRAY['guide-leonida', 'guide-leonida-2']::text[], 'trailer_inferred', '2025-05-12T00:00:00.000Z', '2025-05-12T00:00:00.000Z'),
  ('gta-6-platforms-and-system-requirements', 'GTA 6 Platforms & System Requirements', 'Which consoles run GTA 6 at launch, and what we can guess about an eventual PC release.', 'Grand Theft Auto VI launches on PlayStation 5 and Xbox Series X|S. There is no last-gen (PS4 / Xbox One) version.

A PC release has not been announced. Any PC system requirements are pure speculation until Rockstar confirms a port.', 'Platforms', 'Beginner', false, ARRAY['guide-platforms']::text[], 'confirmed', '2025-11-09T00:00:00.000Z', '2025-11-09T00:00:00.000Z'),
  ('trailer-1-vs-trailer-2-what-changed', 'Trailer 1 vs Trailer 2: What Changed', 'Side-by-side analysis of the two official trailers and the new details the second one revealed.', 'The first trailer (December 2023) introduced Vice City, Lucia, and the tone of the game. The second trailer (May 2025) widened the lens — showing more of Leonida, a larger supporting cast, and a major visual leap.

This guide compares the two shot by shot.', 'Analysis', 'Advanced', false, ARRAY['guide-trailers']::text[], 'trailer_inferred', '2025-05-14T00:00:00.000Z', '2025-05-14T00:00:00.000Z'),
  ('gta-6-pre-order-and-editions', 'GTA 6 Pre-Orders & Editions: What to Expect', 'Pre-orders aren''t live yet — here''s what Rockstar''s past launches suggest may be coming.', 'Rockstar has not opened pre-orders or detailed special editions for Grand Theft Auto VI. Based on prior launches, expect standard and premium editions with in-game bonuses to be announced closer to release.

Treat any edition details circulating now as unconfirmed.', 'Buying', 'Beginner', false, ARRAY['guide-preorder']::text[], 'speculation', '2025-12-02T00:00:00.000Z', '2025-12-02T00:00:00.000Z')
on conflict (slug) do update set title = excluded.title, description = excluded.description, body = excluded.body, category = excluded.category, difficulty = excluded.difficulty, featured = excluded.featured, status = excluded.status, created_at = excluded.created_at, updated_at = excluded.updated_at;

-- vehicles (10)
delete from vehicles where slug not in ('grotti-cheetah-95', 'schyster-deviant', 'vapid-dominator-buggy-67', 'dinka-enduro', 'crest-kayak', 'declasse-mamba-gt', 'vapid-riata-classic', 'sirius', 'shitzu-squalo', 'vapid-stanier-55');
insert into vehicles (slug, title, description, body, class, manufacturer, images, status, top_speed, created_at, updated_at) values
  ('grotti-cheetah-95', 'Grotti Cheetah ''95', 'A mid-''90s mid-engine exotic — the Cheetah returns, channeling the Ferrari Testarossa and 512 BB.', 'Confirmed in the Ultimate Edition lineup, the Grotti Cheetah ''95 is a classic mid-engine supercar inspired by the Ferrari Testarossa and 512 BB. Performance figures are estimates pending official stats.', 'Sports Classics', 'Grotti', ARRAY['/images/vehicles/grotti-cheetah-95.jpg']::text[], 'confirmed', 195, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('schyster-deviant', 'Schyster Deviant', 'Early-''70s American muscle inspired by the 1972 AMC Javelin.', 'An Ultimate Edition muscle car drawing on the 1972 AMC Javelin — long hood, aggressive stance, classic V8 energy.', 'Muscle', 'Schyster', ARRAY['/images/vehicles/schyster-deviant.jpg']::text[], 'confirmed', 130, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('vapid-dominator-buggy-67', 'Vapid Dominator Buggy ''67', 'An off-road build of a first-generation Ford Mustang — rugged and trail-ready.', 'Part of the Ultimate Edition pack, the Dominator Buggy ''67 reimagines a first-generation Ford Mustang as a raw off-road machine.', 'Off-Road', 'Vapid', ARRAY['/images/vehicles/vapid-dominator-buggy-67.jpg']::text[], 'confirmed', 120, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('dinka-enduro', 'Dinka Enduro', 'A dual-sport motorcycle inspired by classic Honda XL350, XR500 and CB models.', 'An Ultimate Edition dual-sport bike channeling vintage Honda XL350, XR500 and CB motorcycles — equally at home on road and trail.', 'Motorcycle', 'Dinka', ARRAY['/images/vehicles/dinka-enduro.jpg']::text[], 'confirmed', 95, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('crest-kayak', 'Crest Kayak', 'A paddle kayak for exploring Leonida''s waterways — based on the Crescent Kayak.', 'An Ultimate Edition watercraft based on the Crescent Kayak, ideal for quietly navigating the wetlands and coast of Leonida.', 'Boat', 'Crest', ARRAY['/images/vehicles/crest-kayak.jpg']::text[], 'confirmed', 8, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('declasse-mamba-gt', 'Declasse Mamba GT', 'A ''60s racing coupe inspired by the Shelby Daytona Coupe.', 'An Ultimate Edition sports classic modeled on the Shelby Daytona Coupe — a sleek, race-bred grand tourer.', 'Sports Classics', 'Declasse', ARRAY['/images/vehicles/declasse-mamba-gt.jpg']::text[], 'confirmed', 160, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('vapid-riata-classic', 'Vapid Riata Classic', 'A classic off-road SUV channeling the first-generation Ford Bronco.', 'An Ultimate Edition SUV inspired by the first-generation Ford Bronco — boxy, capable, and built for the backcountry.', 'SUV', 'Vapid', ARRAY['/images/vehicles/vapid-riata-classic.jpg']::text[], 'confirmed', 105, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('sirius', 'Sirius', 'A 1970s muscle car inspired by the 1970 Mercury Cougar.', 'An Ultimate Edition muscle car drawing on the 1970 Mercury Cougar — long, low, and unmistakably American.', 'Muscle', 'Unconfirmed', ARRAY['/images/vehicles/sirius.jpg']::text[], 'confirmed', 135, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('shitzu-squalo', 'Shitzu Squalo', 'A sleek speedboat for tearing across the Leonida coast.', 'An Ultimate Edition speedboat built for the open water around Vice City and the Leonida Keys.', 'Boat', 'Shitzu', ARRAY['/images/vehicles/shitzu-squalo.jpg']::text[], 'confirmed', 90, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z'),
  ('vapid-stanier-55', 'Vapid Stanier ''55', 'A vintage 1955 sedan — free with every pre-order via the Vintage Vice City Pack.', 'The ''55 Vapid Stanier is a classic 1950s sedan included with every pre-order as part of the Vintage Vice City Pack, alongside an Ocean Beach garage. It''s the first GTA 6 vehicle Rockstar named.', 'Sedan', 'Vapid', ARRAY['/images/vehicles/vapid-stanier-55.jpg']::text[], 'confirmed', 90, '2026-06-25T00:00:00.000Z', '2026-06-25T00:00:00.000Z')
on conflict (slug) do update set title = excluded.title, description = excluded.description, body = excluded.body, class = excluded.class, manufacturer = excluded.manufacturer, status = excluded.status, top_speed = excluded.top_speed, created_at = excluded.created_at, updated_at = excluded.updated_at;

-- characters (8)
insert into characters (slug, title, description, body, role, affiliation, images, status, voice_actor, created_at, updated_at) values
  ('lucia-caminos', 'Lucia Caminos', 'The series'' first female protagonist — out on parole with everything to prove.', 'Lucia Caminos is one of two playable protagonists in Grand Theft Auto VI and the first female lead in the mainline series. Introduced in the first trailer leaving a Leonida correctional facility, she''s out on parole — an ankle monitor appears in several Trailer 2 scenes, a reminder she''s still being watched. Her relationship with Jason is the emotional core of the story, a partnership Rockstar frames as a modern Bonnie and Clyde.', 'Protagonist', 'Jason & Lucia', ARRAY['/images/characters/lucia-caminos.jpg']::text[], 'confirmed', NULL, '2023-12-04T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('jason-duval', 'Jason Duval', 'Lucia''s partner — ex-Army, now running jobs for a Keys drug smuggler and wanting out.', 'Jason Duval is the second playable protagonist. He grew up around criminals, joined the US Army to try to straighten his life out, and ended up in the Leonida Keys doing jobs for drug smuggler Brian Heder — living rent-free in exchange for dirty work. He wants an easy life, but trouble keeps finding him and Lucia.', 'Protagonist', 'Jason & Lucia', ARRAY['/images/characters/jason-duval.jpg']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('cal-hampton', 'Cal Hampton', 'Jason''s loyal buddy — happiest at home with a beer and the Coast Guard radio.', 'Cal Hampton is Jason''s friend who feels safest at home, drinking beers and listening to Coast Guard comms. Loyal but not the ambitious type, he''s Jason''s connection to chatter and information from the fringes.', 'Associate', 'Jason''s circle', ARRAY['/images/characters/cal-hampton.jpg']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('boobie-ike', 'Boobie Ike', 'A Vice City legend who turned street life into real estate, a strip club, and a record label.', 'Boobie Ike is a Vice City legend who turned the street life into real business — real estate, a strip club called the Jack of Hearts, and a recording studio. He''s partnered with music hustler Dre''Quan Priest.', 'Businessman', 'Vice City', ARRAY['/images/characters/boobie-ike.jpg']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('drequan-priest', 'Dre''Quan Priest', 'A music hustler running Only Raw Records, betting on the rap duo Real Dimez.', 'Dre''Quan Priest is a music hustler who runs Only Raw Records and signed the viral rap duo Real Dimez. Partnered with Boobie Ike, he''s chasing a breakout out of Leonida''s music scene.', 'Music Mogul', 'Only Raw Records', ARRAY['/images/characters/drequan-priest.jpg']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('real-dimez', 'Real Dimez', 'The viral rap duo signed to Only Raw Records.', 'Real Dimez is a rap duo signed to Dre''Quan Priest''s Only Raw Records — internet-famous performers riding their viral moment in Leonida''s music scene.', 'Rap Duo', 'Only Raw Records', ARRAY['/images/characters/real-dimez.jpg']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('raul-bautista', 'Raul Bautista', 'A bank robber assembling the crew for the score that kicks off the story.', 'Raul Bautista is an experienced robber putting together a crew for ambitious jobs. The bank robbery he sets up looks to be the heist that kicks off the whole story — pulling Jason and Lucia toward serious risk.', 'Robber', 'Bautista crew', ARRAY['/images/characters/raul-bautista.jpg']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('brian-heder', 'Brian Heder', 'The older drug smuggler Jason works for in the Keys.', 'Brian Heder is an older drug smuggler operating out of the Leonida Keys. He lets Jason live rent-free in exchange for doing his dirty work — one of the figures whose business pulls Jason deeper in.', 'Smuggler', 'Leonida Keys', ARRAY['/images/characters/brian-heder.jpg']::text[], 'confirmed', NULL, '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z')
on conflict (slug) do update set title = excluded.title, description = excluded.description, body = excluded.body, role = excluded.role, affiliation = excluded.affiliation, status = excluded.status, voice_actor = excluded.voice_actor, created_at = excluded.created_at, updated_at = excluded.updated_at;

-- locations (6)
insert into locations (slug, title, description, body, region, type, coordinates, images, status, created_at, updated_at) values
  ('vice-city', 'Vice City', 'Rockstar''s modern reimagining of Miami — the neon-soaked heart of Leonida.', 'Vice City returns as the centerpiece of Grand Theft Auto VI — a modern reimagining of Miami and the primary urban center of Leonida. Beaches, Art Deco facades, nightlife, and a dense, vertical skyline define the city at the heart of the map.', 'Vice City', 'City', '{"x":64,"y":68}'::jsonb, ARRAY['loc-vicecity', 'loc-vicecity-2']::text[], 'confirmed', '2023-12-04T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('leonida-keys', 'Leonida Keys', 'An island chain based on the Florida Keys — Jason''s home turf.', 'The Leonida Keys are an island chain based on the real Florida Keys, with scenic coastal highways linking sun-bleached islands. It''s where Jason lives at the start of the game, running jobs for smuggler Brian Heder.', 'Leonida Keys', 'Islands', '{"x":58,"y":90}'::jsonb, ARRAY['loc-keys']::text[], 'confirmed', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('grassrivers', 'Grassrivers', 'Rockstar''s take on the Everglades — swamps, marshland, and isolated rural communities.', 'Grassrivers is Leonida''s wetlands region, inspired by the Florida Everglades: swamps, marshland, slow-moving rivers, cypress forests, and isolated rural communities. Trailer footage shows airboats skimming across the water.', 'Grassrivers', 'Wetlands', '{"x":46,"y":76}'::jsonb, ARRAY['loc-grassrivers']::text[], 'confirmed', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('port-gellhorn', 'Port Gellhorn', 'Leonida''s ''forgotten coast'' — cheap motels, shut-down attractions, and empty strip malls.', 'Port Gellhorn is Leonida''s forgotten coast — a grittier counterpoint to Vice City''s glamour, with cheap motels, shuttered roadside attractions, and empty strip malls along a faded panhandle shoreline.', 'Port Gellhorn', 'Town', '{"x":22,"y":26}'::jsonb, ARRAY['loc-portgellhorn']::text[], 'confirmed', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('ambrosia', 'Ambrosia', 'Old-school industrial heartland — home to the Allied Crystal sugar refinery.', 'Ambrosia is where American industry and old-school values reign — inland country anchored by the Allied Crystal sugar refinery. It''s described as ''what''s keeping Leonida sweet,'' a working-town contrast to the glitz of the coast.', 'Ambrosia', 'Town', '{"x":40,"y":48}'::jsonb, ARRAY['loc-ambrosia']::text[], 'confirmed', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z'),
  ('mount-kalliga', 'Mount Kalaga', 'Leonida''s elevated highlands — forests, lakes, and dangerous wildlife.', 'Mount Kalaga is Leonida''s highland region — forested terrain with lakes, rivers, and mountains, often compared to Red Dead Redemption 2''s Ambarino. Expect dangerous wildlife including bears and panthers far from the city lights.', 'Mount Kalaga', 'Wilderness', '{"x":52,"y":30}'::jsonb, ARRAY['loc-kalliga']::text[], 'confirmed', '2025-05-06T00:00:00.000Z', '2025-05-06T00:00:00.000Z')
on conflict (slug) do update set title = excluded.title, description = excluded.description, body = excluded.body, region = excluded.region, type = excluded.type, coordinates = excluded.coordinates, status = excluded.status, created_at = excluded.created_at, updated_at = excluded.updated_at;

-- carousel_items (4)
delete from carousel_items;
insert into carousel_items (title, category, image, href, date, "order", active, status) values
  ('GTA 6 Launches November 19, 2026', 'Release', 'news-release-date', '/news/gta-6-release-date-november-19-2026', '2025-11-06T00:00:00.000Z', 1, true, 'confirmed'),
  ('Trailer 2: Everything Rockstar Revealed', 'Trailer', 'news-trailer2', '/news/trailer-2-everything-revealed', '2025-05-06T00:00:00.000Z', 2, true, 'confirmed'),
  ('Meet Jason & Lucia, the Dual Protagonists', 'Characters', 'news-jason-lucia', '/news/jason-and-lucia-dual-protagonists', '2023-12-05T00:00:00.000Z', 3, true, 'confirmed'),
  ('The State of Leonida: Confirmed Regions', 'World', 'news-leonida', '/news/leonida-state-confirmed-locations', '2025-05-09T00:00:00.000Z', 4, true, 'trailer_inferred');
